language: node_js
sudo: false
node_js:
  - 8.14
  - 10.13
  - 11
  - 12
install:
  # install Node.js dependencies
  - travis_retry npm ci
script:
  # run test suite
  - travis_retry npm test
after_success:
  # udpate coverate stats
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
