AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Sample function using multiple layers to require BS4 and LXML in Python 3.6
Resources:
  bs4Layer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: bs4-python36
      Description: Beautiful Soup 4 Layer for Python 3.6
      ContentUri: ./layers/bs4-layer/bs4-python36-layer.zip
      CompatibleRuntimes:
        - python3.6
      RetentionPolicy: Retain
  getEvangelistsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./functions/get_evangelists
      Description: A function to get evangelist headshots and log gender/age about each.
      MemorySize: 128
      Timeout: 30
      Policies:
        - RekognitionDetectOnlyPolicy: {}
      Layers:
        - Ref: bs4Layer
  